---
title: "Regressors"
description: |
  This project will explore the use of Geographically Weighted Regression analysis on region with high COVID infection rate, specifically, Jakarta, the main city of Indonesia.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Project Title

Regressors: Geographically Weighted Regression on Jakarta COVID-19 cases

# Abstract

COVID-19 has become an indisputable part of our daily life ever since the virus spread to the majority of the world. Some countries are able to keep the situation under control, while some suffer the devastating effects from it. Among Asia countries, Indonesia has the highest COVID related mortality and positive rates for COVID-19 cases (Worldometers, n.d.), mainly in Jakarta, the main capital. This is likely due to certain underlying common factors within the countries. Researchers claimed that Jakarta could have as many as 4.7 million people who are possibly infected by the virus in March 2021 (Sood, 2021). This is alarming as this number constitutes to “nearly half” of Jakarta’s population. After our group was made aware about the seriousness of this matter, we decided to come up with Regressors, a Geographically Weighted Regression (GWR) application, to investigate the impacts of various variables (independent variable) on the mortality and positive rates (dependent variable).
  
This application aims to allow users to import a dataset of their preference and use it to identify the relationship between the selected independent variables, such as proximity to healthcare facilities and proximity to attraction, and the dependent variable, such as Number of positive COVID cases. Functions include Exploratory Data Analysis (EDA), GWR, GWR prediction model. EDA visualizes the different variables on spatial point map and Histogram. GWR builds a GWR model based on selected dependent and independent variables, provides analysis on their relationship, thus allowing users to select the best parameters for the GWR base model. Additionally, users are able to visualize the accuracy of the model geographically. GWR prediction model is built based on selected dependent and independent variables with the dataset provided. The output is the predicted values which will be analyzed and visualized geographically on the interactive map. 
  
# Links

- [Github](https://github.com/nxinyan/IS415_project)
- [Project Proposal](ProjectProposal.html)
- [Poster](./Poster/Poster.pdf)
- [Research Paper](./Research\ Paper/Research_Paper.pdf)
- [User Guide for ShinyApp](UserGuide.html)
- [ShinyApp.io](https://junlong-toh-2019-is415.shinyapps.io/Regressors)
